services:
  api:
    container_name: featureflag.api
    build:
      context: .
      dockerfile: FeatureFlagEngine.Api/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings:FeatureFlagsDb=Host=postgres;Port=5432;Database=featureflags;Username=postgres;Password=postgres
      - RedisSettings:CacheServer=redis:6379
    depends_on:
      - postgres
      - redis

  postgres:
    container_name: featureflag.postgres
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: featureflags
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    container_name: featureflag.redis
    image: redis:7
    ports:
      - "6379:6379"
    restart: always

volumes:
  pgdata:
